name: murthy-electron-hello-world-kiosk
version: 0.1
summary: Hello World Electron app for a Kiosk
description: |
  Simple Hello World Electron app as an example of a HTML5 Kiosk
confinement: strict
grade: devel

apps:
  murthy-electron-hello-world-kiosk:
    daemon: simple
    restart-condition: always
    command: desktop-launch xwayland-kiosk-launch "$SNAP/electron-helloworld/electron-quick-start"
    environment:
      XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"
    slots: [ x11 ]
    plugs:
    - browser-sandbox
    - network
    - network-bind
    - opengl
    - pulseaudio
    - wayland
    - x11-plug

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11

parts:
  electron-helloworld:
    plugin: nodejs
    source: https://github.com/electron/electron-quick-start.git
    after: [desktop-gtk2, xwayland-kiosk-helper]
    override-build: |
        case $SNAPCRAFT_ARCH_TRIPLET in
          "i386-linux-gnu") ARCH="ia32";;
          "x86_64-linux-gnu") ARCH="x64";;
          "arm-linux-gnueabihf") ARCH="armv7l";;
          "aarch64-linux-gnu") ARCH="arm64";;
          *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
        esac
        npm install electron-packager &&
        ./node_modules/.bin/electron-packager . --overwrite --platform=linux --arch=$ARCH --output=release-build --prune=true
        cp -v -R ./electron-quick-start-linux-$ARCH $SNAPCRAFT_PART_INSTALL/electron-helloworld
    stage-packages:
    - libasound2
    - libgconf-2-4
    - libnss3
    - libxss1
    - libxtst6
